### ISSUE TITLE
Feature request: Add a command to add the current file root directory to the list

### ISSUE THREAD

**Issue by Parsifa1** [coffebar/neovim-project#14]
Anyway, this is still a great plugin! The function of retaining sessions is so easy to use.

**Comment by coffebar** [comment]
Thanks, unfortunately, this feature will not be available. 
All project directories (or their masks) must be in your plugin configuration, that is beyond the scope of the plugin itself.
You need to organize your projects and maintain this order so that you don't need to add anything later.

**Comment by Parsifa1** [comment]
OK, thank you anyway!

**Comment by xlboy** [comment]
sometimes I want to add a project to the project list that is not under the **directory rules**(`opts.projects[...]`), such as some plugins loaded in `lazy.nvim` (because I want to debug these additional plugin projects)

It would be great if there were both **automatic** and **manual** options available

**Comment by coffebar** [comment]
Hi, I suggest you to add a mask with "*", that will suit all lazy plugins. You will not see any of them in the project history, but if you will need one, open it once from the discovery command and it will be with you, saved to the history. Good luck, hope this helps

**Comment by xlboy** [comment]
> Hi, I suggest you to add a mask with "*", that will suit all lazy plugins. You will not see any of them in the project history, but if you will need one, open it once from the discovery command and it will be with you, saved to the history. Good luck, hope this helps

Thank you for your answer! I actually tried this before, but it would cause some performance loss when Neovim starts, so I decided to remove it later. T-T

**Comment by coffebar** [comment]
I am glad that you have guessed to use this software in the same way as I intended it.
But, of course, it is very unfortunate that you have a problem with the performance.
if you have modern equipment and no speed problems with SSD, try to localize the issue if you can. Maybe it's a built-in vim function that searches for files by mask.  If this is confirmed, we can look for ways to speed up work, for example, by replacing this function with something else (Idk, ripgrep maybe).
