### ISSUE TITLE
Project per tab

### ISSUE THREAD

**Issue by GRVYDEV** [coffebar/neovim-project#20]
Hi, would it be possible to omit tabs from being associated with a project? I would like to have multiple tabs open with multiple different projects.

**Comment by coffebar** [comment]
The only option related to this I can find is `:set sessionoptions-=tabpages`
Didn't test how it works. Not sure you need exactly this behavior, but you can try.

For me, mappings for projects switching works very similar to what you want. I can switch to the previous project without a telescope, or to any other with it. Quick jumping from project to project achieved + possible to use tabs inside the project (some of plugins spawn tabs and it's convenient to close these tabs to close split windows)

**Comment by thuvasooriya** [comment]
I'm trying to use this with NVchad and cannot get it to ignore tabpages, I tried removing tabpages from sessionoptions still it removes all the tabs and switches the session when I select a project from my telescope. What am I doing wrong?
I'm a beginner trying the lua stuff for the first time, so If I have any dumb mistakes, please point them out. Thanks
```
  {
    "coffebar/neovim-project",
    opts = overrides.nvimproject,
    init = function()
      -- enable saving the state of plugins in the session
      vim.opt.sessionoptions:append "globals" -- save global variables that start with an uppercase letter and contain at least one lowercase letter.
      vim.opt.sessionoptions:remove "tabpages"
    end,
    dependencies = {
      { "nvim-lua/plenary.nvim" },
      -- { "nvim-telescope/telescope.nvim", tag = "0.1.4" },
      { "Shatur/neovim-session-manager" },
    },
    lazy = false,
    priority = 100,
  },

```

**Comment by coffebar** [comment]
You're doing right, this option is just working not the way you want.
The only advice from me is to change workflow as I mentioned before
