### ISSUE TITLE
[Feature Request] Loading a Project Directly

### ISSUE THREAD

**Issue by matthewKeville** [coffebar/neovim-project#22]
I would like to be able to manually load a 'project'. To my understanding this would require exposing some of the extant functionality inside `lua/neovim-project/utils/history.lua` and `lua/neovim-project/project.lua` to a public API.

[lua/neovim-project/utils/history.lua](https://github.com/coffebar/neovim-project/blob/e7868b38f402be94e859d479002df1418bc1e954/lua/neovim-project/utils/history.lua#L114C1-L117C4)
```
function M.get_recent_projects()
  M.make_sure_read_projects_from_history()
  return sanitize_projects()
end
```

[lua/neovim-project/project.lua](https://github.com/coffebar/neovim-project/blob/e7868b38f402be94e859d479002df1418bc1e954/lua/neovim-project/project.lua)
```
M.switch_project = function(dir)
  if M.in_session() then
    M.switch_after_save_session(dir)
  else
    M.load_session(dir)
  end
end
```
I think some wrapper around these two functions should suffice.

**Comment by coffebar** [comment]
Hi, these functions are exposed to a module level, so you can call them outside, right? What's missing?

**Comment by matthewKeville** [comment]
It didn't appear to me that these modules were meant to be consumed externally. Are they?

**Comment by coffebar** [comment]
It's obviously not an API, but you can use these methods for your personal needs. 
I think this will not change soon
