### ISSUE TITLE
[Feature Request] Option to disable autoloading completely

### ISSUE THREAD

**Issue by coffebar** [coffebar/neovim-project#24]
Put reaction to this post if you want an option to disable autoloading, even if you're opening neovim in project directory.

#5
#23

**Comment by coffebar** [comment]
As an alternative, create an alias to open the neovim with an argument and the session will not be loaded.

```bash
# You may need to adjust this to your starter plugin behavior. 
alias vv="nvim -c bd -- _" # It opens a file "_" and closes it on startup. 
```

**Comment by xzbdmw** [comment]
yes, autoloading is conflict with dashboard.

**Comment by PixsaOJ** [comment]
Provided alias also opens empty buffer which causes dashboard to not load

**Comment by coffebar** [comment]
Option `dashboard_mode` added. Set it to `true` if you want to use dashboard plugins on startup

[Readme ](https://github.com/coffebar/neovim-project?tab=readme-ov-file#%EF%B8%8F-configuration)
