### ISSUE TITLE
[Feature Request] Load `exrc` files like `.nvim.lua` on Project loading

### ISSUE THREAD

**Issue by Aman9das** [coffebar/neovim-project#25]
### Problem

Say one wants to open `~/proj1/` as a project.
The [`exrc`](https://neovim.io/doc/user/starting.html#exrc) option is enabled.
Structure of `proj1`:
```
proj1
├── .nvim.lua
├── index.qmd
└── post1.qmd
```
`.nvim.lua` enables the project specific configurations.

1. They can `nvim ~/proj1` to open the project.
Neovim starts up in `~/proj1`.
As a result `.nvim.lua` configuration file is run.
2. Or they may start neovim as `nvim`.
**Then** switch to the project by running `Telescope neovim-project discover` command.
But the `.nvim.lua` project configuration isn't run.

This difference makes method 2 inferior for opening projects.

### Expected behavior

The benefit of method 2 of opening projects:
- We can create a general Neovim application shortcut.
- We can switch between projects in the same session, and load the corresponding configurations.

Method 2 should also invoke and get the benefits of `.nvim.lua` exrc configuration file.

### Note

As specified here [here](https://github.com/neovim/neovim/issues/27489), the main reason this isn't implemented yet is security. And since in neovim-project the projects are listed manually, it should be safe to allow `.nvim.lua` to run.

**Comment by coffebar** [comment]
user's lua files execution is beyond the scope of this project. The concept of security and how [such a plugin](https://github.com/klen/nvim-config-local) should work is quite subjective.  I even tried to write my own plugin and used it for a while. The main problem is that among them there is no one that will suit everyone and become standard.

You can use autocmd to implement this feature in your dotfiles or in the separate plugin. 

```lua
local augroup = vim.api.nvim_create_augroup("user_cmds", { clear = true })
vim.api.nvim_create_autocmd("User", {
  pattern = { "SessionLoadPost" },
  group = augroup,
  desc = "Run lua file after loading session",
  callback = function()
    -- ...todo
  end,
})

**Comment by Aman9das** [comment]
Thanks for the tip
