### ISSUE TITLE
[Feature request] set terminal window to CWD of project

### ISSUE THREAD

**Issue by jasonshanks** [coffebar/neovim-project#32]
Not sure if this is possible but when I switch projects within Neovim, the terminal directory remains in the previous directory (I’m using tmux).

consequently if I open up a new pane (for instance to manage server operations for the project), it inherits this unrelated directory.

I’ve gotten around this a bit by adding a keymap:
`keymap.set(“n”, “<leader>t”, “:silent !tmux split-window -c %:p:h<CR>”, {silent = true})`

which opens a split lane below in the CWD of neovim, 
but this doesn’t fix the main pane directory that neovim project is running in.

consequently, that new pane I open persists in that directory as well, so (maybe there’s already a way) if one could run a post-project switching command, I could force it to close that pane before switching out of the project.

if this is beyond scope I totally understand, will look at tmux session managers like the old tmuxifier instead.

**Comment by coffebar** [comment]
Normally, neovim-project [sets option](https://github.com/coffebar/neovim-project/blob/771ccd6d7969d19bd84489d1fbae2541c5b9b9c7/lua/neovim-project/config.lua#L47C3-L47C29) `vim.opt.autochdir = false` on init (to avoid changing the current directory to the directory of the current file) 
and changes cwd for neovim [on every project loading](https://github.com/coffebar/neovim-project/blob/771ccd6d7969d19bd84489d1fbae2541c5b9b9c7/lua/neovim-project/project.lua#L136) via `vim.api.nvim_set_current_dir(dir)`.

I'm using terminals inside neovim (like [ToggleTerm](https://github.com/akinsho/toggleterm.nvim) or default terminal mode) and splits (`:split`, `:vsplit`) and my terminal’s working directory is always project root by default.

If I understand correctly, you want tmux to store the current project directory path and pass it between panels, right?
Unfortunately, I am not a tmux user. I'm unlikely to give good advice. Maybe you need to set up some autocmd in your neovim config, like  
```lua
vim.api.nvim_create_autocmd({ "DirChanged" }, { 
    pattern = "global",
    -- group = augroup,
    callback = function(event)
         --- actions to set CWD for parent terminal
    end
})
```

**Comment by jasonshanks** [comment]
@coffebar ToggleTerm is the way! Thank you so much 🙏  It's quick float is exactly all I needed and I now have that totally setup as a working replacement with the same key mapping. Very similar to how I'm using LazyGit in a quick float.

I can see how you wouldn't want nevoid-project to set option to autochdir as you'd end up down in some subfolder as the root, not desirable.

For completion, I did take a stab at setting up an autocmd, tried both of these actions but they didn't produce any results, not sure if the (event) needs to actually pass in when neovim-project changes directory?

```
   vim.fn.system("tmux set-environment -g TMUXPWD $(pwd)")
   os.execute("tmux set-environment -g TMUXPWD $" .. vim.fn.getcwd())
```

Maybe someone better knowledgeable about tmux than me can shed light. Otherwise happy for you to close this since it probably off topic now.

Greatly appreciate your suggestion, and excellent plugin!!
