### ISSUE TITLE
Replace Ctrl+d

### ISSUE THREAD

**Issue by Ordeeper** [coffebar/neovim-project#44]
How to replace the keymap Ctrl+d?

**Comment by coffebar** [comment]
This line is located in the telescope extension code:
```        map("i", "<c-d>", delete_project)```
Unfortunately there's no option for this now. 

Probably you can suggest a PR to make it configurable. 
Or wait until I will do it.

1. this option should work for telescope and fzf  
2. one key map for insert mode and second one for normal mode 
3. documentation should be updated in readme and in vim doc, default config will be changed too
