### ISSUE TITLE
Duplicate projects folders 

### ISSUE THREAD

**Issue by Krymancer** [coffebar/neovim-project#46]
I'm seem my project folders duplicated like this:

![image](https://github.com/user-attachments/assets/ce1d5060-28ee-465e-aac2-b292c7dd7d74)

Can you help me? I didn't found anything related in issues or in the repo.

**Comment by coffebar** [comment]
I want to help, but I need you to figure out steps to reproduce. It seems you have something special in your setup. 
Do you have some symlinks or hard links on the way to your projects? 

If you run this in nvim command mode:
`:lua vim.notify(vim.inspect(vim.fn.glob("~/projects/*", true, true, true)))`

Do you see it doubles? Normally it should not

**Comment by coffebar** [comment]
Added extra check for duplicates, try latest version. If this does not help, I would blame Telescope

**Comment by Krymancer** [comment]
Still seeing duplicates, I will try on another computer

I tried to use fzf-lua instead and same thing.

```lua
return {
	"coffebar/neovim-project",
	opts = {
		projects = { -- define project roots
			"~/projects/*",
		},
		picker = {
			type = "fzf-lua", -- or "fzf-lua"
		},
	},
	init = function()
		-- enable saving the state of plugins in the session
		vim.opt.sessionoptions:append("globals") -- save global variables that start with an uppercase letter and contain at least one lowercase letter.
	end,
	dependencies = {
		{ "nvim-lua/plenary.nvim" },
		{ "ibhagwan/fzf-lua" },
		{ "Shatur/neovim-session-manager" },
	},
	lazy = false,
	priority = 100,
	config = function()
		require("neovim-project").setup()
	end,
}
```

**Comment by coffebar** [comment]
try again the latest version, that previous fix was not perfect

**Comment by Krymancer** [comment]
Working perfectly, thank you so much
