### ISSUE TITLE
Feature request. Make restart last session when opening optional.

### ISSUE THREAD

**Issue by dcarrillo** [coffebar/neovim-project#5]
Hi there,

Thank you for this plugin. It is by far the best project manager for Neovim that I've tested so far, and it **actually** works :)

Your first feature is "Start where you left off last time." That's great, but I was wondering if this could be optional. I'm using [mini.starter](https://github.com/echasnovski/mini.starter) when I open Neovim without a path parameter, and I'd love to use both plugins together. I didn't see any parameter in the [config](https://github.com/coffebar/neovim-project#%EF%B8%8F-configuration) documentation.

Thank you in advance.

**Comment by coffebar** [comment]
Done. Now you can add `last_session_on_startup = false,` to your config

**Comment by dcarrillo** [comment]
Thank you :)
