### ISSUE TITLE
Feature request: add command to quickly switch to previous session

### ISSUE THREAD

**Issue by yvesjans** [coffebar/neovim-project#6]
Thank you for this wonderful plugin!

Sometimes I need to quickly switch between two projects (e.g. to reference something). Would it be possible to add a command to switch to the last session? Then a single keystroke key binding could be added to call this command.

**Comment by coffebar** [comment]
Sounds like a good idea

**Comment by coffebar** [comment]
@yvesjans Can you test it please and give feedback?

I pushed this feature to the branch [load_recent](https://github.com/coffebar/neovim-project/tree/load_recent).
So it will be available for you when you add a branch option to your plugin manager.

```lua
-- where you install neovim-project
branch = "load_recent",
```

**Comment by coffebar** [comment]
`:NeovimProjectLoadRecent`

btw, you can add `[count]` prefix to command, like `:2NeovimProjectLoadRecent` to move up in history by this number

**Comment by yvesjans** [comment]
@coffebar that works perfectly, including the count prefix, thanks a lot!

**Comment by coffebar** [comment]
merged into main
