### ISSUE TITLE
Hey there

### ISSUE THREAD

**Issue by 9mm** [coffebar/neovim-project#8]
It looks like the `ahmedkhalf/project.nvim` project is dead and maintainer won't appoint anyone else (or just doesnt answer, which is disappointing because it did exactly what a lot of people needed it seems.

I noticed you removed a lot of existing functionality in your version, such as auto-adding projects based on some matching pattern (like `.git`). Are there any plans to have that sort of functionality back in? Or are you solidified on your idea to have it in a config file?

**Comment by coffebar** [comment]
`ahmedkhalf/project.nvim` is a nice plugin, I believe it works. I was using a custom fork of it for a long time, but then I realized that its functionality (project root detection) hinders me more than it helps. I had to create unnecessary files just for the plugin to find the project.
I felt that I was struggling with this functionality, and meanwhile, the roots of projects are static and permanent for me. 

It seems to me that this problem has a very simple solution. I think that the best approach is to decide once for yourself where the roots of the projects will be.
As an exception, you can make changes to the config when you change your mind.

`neovim-project` is not a fork of `project.nvim` , I do not plan to take any functionality from it. Now everything suits me as it is.

However, if you have ideas on how to improve, suggestions and PR are welcome!

**Comment by 9mm** [comment]
I agree, I originally liked the idea of static projects better anyway, although I prefer the way of https://github.com/nvim-telescope/telescope-project.nvim than a config file (in this plugin you just push `<C-a>` to auto-add the directory to the project list, so no manual plugin editing is necessary.

With that said, if someone were to add simple auto project detection based on something like a `.git` file, would that be accepted? I'm trying to get away from the other plugin as he doesn't maintain it and there are some things I want like customizing keymaps, as well as other PRs just sitting there.

If I did move to this one, which I'm not against, I do think the workflow would be good to have some way to add projects within vim, as editing config files also has the downside of preventing me from committing my `.dotfiles` without modifications (for internal project folder names, etc)

**Comment by coffebar** [comment]
If you want to share dotfiles without leaking what are you doing,  I suggest using glob.
For example, you have projects directory called `HackedBanks`, that contains projects like `BankOfAmerica` and other banks.
BankOfAmerica has a sub-project called `ManagersFacebook`. You want to have a project for each folder in `HackedBanks` and also for `ManagersFacebook`. 

```lua
  opts = {
    projects = { 
      "~/Ha*anks/*", -- will be expanded to HackedBanks/*
      "~/Ha*anks/*/Man*book", -- `ManagersFacebook` will be a project for each bank
    },
  },
```

The concept of this plug-in is based on the config patterns. It will not be very easy to create a mapping to add projects that do not match patterns. 

I believe for most cases is enough to use something like this:

```lua
  opts = {
    projects = { 
      "~/pets/*",
      "~/courses/*",
      "~/work/*",
    },
  },
```

**Comment by giulianisanches** [comment]
Sorry to comment out on a close issue, but i thought it would be better then create a new one for an extended version of the same question.

I'm also used to editors with plugins that recognize `.git` (or any other vcs tool) directories as a project or you can set like custom `.project` files.

Now that i'm trying to migrate out of VSCode and searching for a plugin that works as close as possible to this. telescope-project.nvim is kind of a good option but your plugins seems to fit more my workflow.

What defines a project for your plugin ? Any folder under the configuration ? eg

```
opts = {
    projects = { 
      "~/pets/*",
    }
}
```

in the above example, if i have the path `~/pets/orange/cat`  will i get have the `orange` or `cat` project ?

**Comment by coffebar** [comment]
Above config gives you a project "orange". If you need both orange and cat, you can do this:
```
opts = {
    projects = { 
      "~/pets/*",
      "~/pets/orange/cat",
    }
}
```
