### ISSUE TITLE
Automatically project corresponding to the first argument if it's a directory

### ISSUE THREAD

**Issue by Ciel-MC** [coffebar/neovim-project#9]
I was surprised that this wasn't already a feature, but it would be really nice if whenever neovim is started with(i.e. `nvim ~/project/something`) a project directory, it automatically switch to that project.

**Comment by Ciel-MC** [comment]
Post was edited because I didn't realize that doing `nvim` in a directory already automatically launches the project, only realized it when I was browsing the code and seeing how I can implement it. Mb

**Comment by coffebar** [comment]
yeah, there really is no such feature.  

sometimes I use it like this  
`cd pets/project && nvim`

You can choose a project through the telescope and it will probably be faster (or the same).

I disable sessions and projects if there is an argument after nvim to be able to use the editor without these features if needed.

I don't think your idea is bad. I might add check if there is a one argument and it's a directory.

**Comment by Ciel-MC** [comment]
> yeah, there really is no such feature.
> 
> sometimes I use it like this `cd pets/project && nvim`
> 
> You can choose a project through the telescope and it will probably be faster (or the same).
> 
> I disable sessions and projects if there is an argument after nvim to be able to use the editor without these features if needed.
> 
> I don't think your idea is bad. I might add check if there is a one argument and it's a directory.

Hey, I made #10 which seems to work, at least for me, though debates can be had that maybe it should be default off, or not a part of this plugin at all by the -100pt rule.

**Comment by Ciel-MC** [comment]
Also, OT but: choosing project thru telescope isn't faster for me, there's actually quite a significant delay(compared to tabbing in terminals) the first time, and not due to slow hardware either, I'm on an M1 MacBook

**Comment by coffebar** [comment]
I will check your PR. 

I'm sorry that you have a delay with the telescope. I don't have that. don't know what it could be
